quarkus.http.port = 2025
quarkus.datasource.jdbc.driver=org.postgresql.Driver

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=administrador
quarkus.datasource.password=agenda123medica
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/agenda_medica
#postgresql://administrador:3aTRqU1N9qpch63mWdO7jyejNSFBnzlq@dpg-d3fkokd6ubrc73bsu8tg-a.oregon-postgres.render.com/agenda_medica

quarkus.hibernate-orm.database.generation=update

#Cross-Origin Resource Sharing (Compartición de Recursos de Orígenes Cruzados).
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
smallrye.jwt.sign.key.location=META-INF/resources/privateKey.pem
mp.jwt.verify.issuer=miapp-issuer
quarkus.smallrye-jwt.enabled=true

# Configuración SMTP de Gmail
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=465
quarkus.mailer.from=agenda.medica.app2025@gmail.com
quarkus.mailer.ssl=true
quarkus.mailer.username=agenda.medica.app2025@gmail.com
quarkus.mailer.password=ojca eaxt vlzb wdnu
quarkus.mailer.mock=false


